//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeLearnLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Workspaces = new HashSet<Workspace>();
        }
    
        public long courseID { get; set; }
        public string courseName { get; set; }
        public string courseCode { get; set; }
    
        public virtual ICollection<Workspace> Workspaces { get; set; }
    }
}
