//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeLearnLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public long docId { get; set; }
        public string docUUID { get; set; }
        public string docType { get; set; }
        public string docContext { get; set; }
        public string docText { get; set; }
        public long docVersion { get; set; }
        public System.DateTime docDate { get; set; }
        public byte[] docTime { get; set; }
        public string docDesc { get; set; }
    
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
