//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeLearnLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public long sessionId { get; set; }
        public long userId { get; set; }
        public long documentId { get; set; }
        public Nullable<long> receiverId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
