//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeLearnLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workspace
    {
        public long workspaceId { get; set; }
        public long userId { get; set; }
        public long courseId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
